version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - python:
            python_version: 3
  pylint:
    enabled: true

exclude_patterns:
  - "**/.venv/"
  - "**/node_modules/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "ui/app/static/"
  - "ui/app/templates/"
