default:
  tags:
    - bachelor

# .lint_job: &lint_job
# .test_job: &test_job

.format_job: &format_job
  image: registry.gitlab.com/hitchhikers/container-images/python-quality:latest

style:
  <<: *format_job
  script:
    - isort --check --diff .
    - black --check --diff .
  allow_failure: true

docs:
  <<: *format_job
  script:
    - pydocstyle
  allow_failure: true

pyright:
  <<: *format_job
  before_script:
    - cd ${MODULE}
    - poetry install
    - source .venv/bin/activate
  script:
    - pyright .
  allow_failure: true
  parallel:
    matrix:
      - MODULE:
          - ml
          - tracing
          - ui

release:
  image: registry.gitlab.com/hitchhikers/container-images/python-quality:latest
  stage: .post
  before_script:
    - npm install -g semantic-release @semantic-release/gitlab
  script:
    - semantic-release
  only:
    - master
