default:
  tags:
    - bachelor

# .lint_job: &lint_job
# .test_job: &test_job

.format_job: &format_job
  image: registry.gitlab.com/hitchhikers/container-images/python-quality:latest

ui-black:
  <<: *format_job
  before_script:
    - cd ${CI_JOB_NAME/-black/}
  script:
    - black --check --diff .
  allow_failure: true

ui-docs:
  <<: *format_job
  before_script:
    - cd ${CI_JOB_NAME/-docs/}
  script:
    - pydocstyle
  allow_failure: true

ui-pyright:
  <<: *format_job
  before_script:
    - cd ${CI_JOB_NAME/-pyright/}
    - poetry install
    - source .venv/bin/activate
  script:
    - pyright .
  allow_failure: true
