[tool.poetry]
name = "code"
version = "0.1.0"
description = """
Application to detect fish and generate a report viewable
inside an iterface before being exported as raw data.
"""
authors = [
"Birger Johan Nordølum",
"Eirik Osland Lavik",
"Kristian André Dahl Haugen",
"Tom-Ruben Traavik Kvalvaag"
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
debugpy = "^1.2.1"
pip = "^21.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
line_length = 80
profile = "black"
multi_line_output = 3

[tool.black]
line-length = 80
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.pytest_cache
    | \.ipynb_checkpoints
    | __pycache__
    | _build
    | buck-out
    | build
    | dist
    | rapport
    | opppgave
    | hdr-bilder
    | venv
    | node_modules
    | README.md
)/
'''
verbose = true
