runs:
  using: composite
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 18
    - name: Build UI
      shell: bash
      run: |
        set -euxo pipefail
        cd src/ui
        npm ci --no-audit
        npm run build:prod
