runs:
  using: composite
  steps:
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: 18
    - name: Build UI
      shell: bash
      run: |
        set -euxo pipefail
        cd src/ui
        npm ci --no-audit
        npm run build:prod
