---
name: build and test ui

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/actions/build-ui"
      - ".github/workflows/test-ui.yaml"
      - "src/ui/package.json"
      - "src/ui/package-lock.json"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.10"
      - uses: ./.github/actions/build-ui
      - run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade tox virtualenv
      - run: |
          python -m scripts.download_weights
      - run: |
          tox -e ui
